.TH "casahdf5support" "1" "2014-10-24" "casacore"
.SH "NAME"
.PP
casahdf5support \- test if casacore is build with HDF5 support
.SH "SYNOPSIS"
.PP
\fBcasahdf5support\fP
.SH "DESCRIPTION"
\fBcasahdf5support\fP is a small tool come with casacore source. It
tests if casacore is build with HDF5 support.
.SH "AUTHOR"
.PP
This manual page was written by Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
