.TH "casacore_memcheck" "1" "2016-03-25" "casacore"
.SH "NAME"
.PP
casacore_memcheck \- use valgrind's memcheck tool on a program
.SH "SYNOPSIS"
.PP
\fBcasacore_memcheck\fP \fIprogram\fR
.SH "DESCRIPTION"
\fBcasacore_memcheck\fP invokes a casacore test program with valgrind
and filter out possible errors to give an overview.

.SH "AUTHOR"
.PP
This manual page was written according to the in-program comments by
Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
