.TH "findmeastable" "1" "2014-10-24" "casacore"
.SH "NAME"
.PP
findmeastable \- show the location where a Measures table is found
.SH "SYNOPSIS"
.PP
\fBfindmeastable\fP \fItabletype\fR
.SH "DESCRIPTION"
\fBfindmeastable\fP is a small tool come with casacore source. It
shows the location where a Measures table is found.
.SH "EXAMPLE"
.TP 8
.B "findmeastable IGRF"
This show the location of \fBIGRF\fP tables.
.SH "AUTHOR"
.PP
This manual page was written by Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
