.TH "image2fits" "1" "2014-10-24" "casacore"
.SH "NAME"
.PP
image2fits \- convert an image to FITS format
.SH "SYNOPSIS"
.PP
\fBimage2fits\fP \fIinput\fR \fIoutput\fR
.SH "DESCRIPTION"
\fBimage2fits\fP is a small tool come with casacore source. It
converts an image to FITS format.
.SH "AUTHOR"
.PP
This manual page was written by Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
