.TH lsmf "1" "2016-03-25" "casacore"
.SH NAME
lsmf \- show meta info of a multifile
.SH SYNOPSIS
\fBlsmf\fP [\fI-b\fR] \fIfilename1\fR ...
.SH DESCRIPTION
\fB-b\fR
show all block numbers (and free blocks)
.SH "AUTHOR"
.PP
This manual page was written according to the in-program comments by
Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
