.TH "measuresdata" "1" "2014-10-24" "casacore"
.SH "NAME"
.PP
measuresdata \- read IERS and other data for Measure conversion
.SH "SYNOPSIS"
.PP
\fBmeasuresdata\fP [\f ... \fR]
.SH "DESCRIPTION"
\fBmeasuresdata\fP is a small tool come with casacore source. It
reads IERS and other data for Measure conversion.
.SH "AUTHOR"
.PP
This manual page was written by Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
