.TH "msselect" "1" "2014-10-24" "casacore"
.SH "NAME"
.PP
msselect \- create a persistent selection of an MeasurementSet
.SH "SYNOPSIS"
.PP
\fBmsselect\fP \fIinput\fP \fIoutput\fP [\fIdeep?\fP] [\fIbaseline\fP]
.SH "DESCRIPTION"
\fBmsselect\fP is a small tool come with casacore source. It
creates a persistent selection of an MeasurementSet.
.PP
\fIdeep?\fP indicates if the output is a deep copy of the MeasurementSet selection.
.PP
\fIbaseline\fP is the selection string for antennae and baselines.
.SH "AUTHOR"
.PP
This manual page was written by Benda Xu <heroxbd@gentoo.org>, for the Debian GNU/Linux system.
